### ISSUE TITLE
Docker Build/Run Error

### ISSUE THREAD

**Issue by BotVue** [kouprlabs/voltaserve#1]
I've downloaded the code and run "docker compose up" and it does setup a few services, but I get these errors below. I have Docker installed on my Macbook Air M1.

1. smtp The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested  0.0s

2. smtp The requested image's platform (linux/amd64) does not match the detected

3. Error response from daemon: Ports are not available: exposing port TCP 0.0.0.0:7000 -> 0.0.0.0:0: listen tcp 0.0.0.0:7000: bind: address already in use

4. CANCELED [builder 4/5] RUN go mod download

5. => ERROR [voltaserve/idp builder 5/5] RUN npm run pkg 

6. => CANCELED [voltaserve/api builder 5/5] RUN go build -o voltaserve-api

**Comment by eliasby** [comment]
@BotVue Thanks for your feedback and the clear error description, I will look into this issue.

The problem is that the Docker image `bytemark/smtp` does not have support for the M1/arm64 architecture.
The long-term solution is to no longer depend on `bytemark/smtp`, replace it with a better Docker based SMTP server, I think I will soon start to work on this.

But for now I suggest you a temporary fix:
- in `docker-compose.yml` remove the `smtp` block, including all `SMTP_HOST` and `SMTP_PORT` environment variables that you will find in `idp` and `api`.
- Set new values for `smtp` in `idp/config.yml` and `api/config.yml`, using your own SMTP server's credentials.
```yaml
smtp:
  host: CHANGE_ME
  port: CHANGE_ME
  username: CHANGE_ME
  password: CHANGE_ME
  senderAddress: no-reply@localhost
  senderName: 'Voltaserve (localhost)'
```
- Delete the containers `voltaserve-api` and `voltaserve-idp`, then `docker compose up` to recreate them.

**Comment by eliasby** [comment]
The reason this happens is because there is something running on your machine that uses the port `9000`.
The port `9000` is used by Voltaserve to run the S3 service which is in this case MinIO.

There are two solutions for this:

Either:
- Find what is using the port `9000` and stop it.

Or:
- in `docker-compose.yml`, under `s3`, replace the port mapping to something like this `"10000:9000"` (where `10000` can be any free port on your machine)
- Then replace every other occurrence of `9000` in `docker-compose.yml` with `10000`. (without touching the one remaining in `s3`) 

Here is a shortened version of the resulting `docker-compose.yml` highlighting only the required changes:
```yaml
s3:
  ports:
    - "10000:9000"
idp:
  environment:
    - S3_URL=http://s3:10000
api:
  environment:
    - S3_URL=s3:10000
```
