### ISSUE TITLE
How can I mount an existing local folder as a volume?

### ISSUE THREAD

**Issue by stancubed** [kouprlabs/voltaserve#295]
### **Question:**

I'm trying to add a local directory so that I can work with it inside a workspace and have those changes reflected in the directory as well. At the moment, it looks like Voltaserve is built to serve fresh bucket content, but how can I get existing data into it? Are there any ways to do this currently or any plans to add this capability?

---

### **Context:**

I've got this deployed via Portainer on Docker in Linux and everything is working very well so far! 

---

### **What have you tried:**

I've tried adding my local dir to minio as a volume, but that doesn't seem to change anything on the service.

```yaml
minio:
    image: minio/minio:RELEASE.2024-04-06T05-26-02Z
    container_name: volta_minio
    networks:
      - voltaserve_default
    ports:
      - ${VOLTASERVE_MINIO_PORT}:9000
      - ${VOLTASERVE_MINIO_CONSOLE_PORT}:9001
    environment:
      MINIO_ROOT_USER: voltaserve
      MINIO_ROOT_PASSWORD: voltaserve
      MINIO_REGION: us-east-1
    volumes:
      - /home/user/storage/digital/ebooks:/data
    command: server /data --console-address ":9001"
```
